[package]
name = "create-gitignore"
version = "0.1.0"
edition = "2021"

[dependencies]
inquire = "0.7.5"
reqwest = { version = "0.12.12", features = ["json"] }
tokio = { version = "1.43.0", features = ["full"] }
